# Site settings
title: Seowonintech Tech Blog
header-img: img/home-bg.jpg
email: tshyeon@seowonintech.co.kr
copyright_name: Seowonintech
description: "seowonintech technology blog" # meta data description
baseurl: 
url: "https://seowonintech.github.io"
twitter_username: 
github_username:  seowonintech
facebook_username:  
email_username:

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
